#!/bin/sh
#
# Usage: cdf
# Description: Change working directory to the top-most Finder window location
# Note: Short for `cdfinder`
#
# credit: https://github.com/mathiasbynens/dotfiles/blob/main/.functions

cdf() { 
	cd "$(osascript -e 'tell app "Finder" to POSIX path of (insertion location as alias)')";
}
