#!/bin/sh
#
# Usage: gz <file>
# Description: Compare original and gzipped file size
#
# credit: https://github.com/mathiasbynens/dotfiles/blob/main/.functions

gz() {
	local origsize=$(wc -c < "$1")
	local gzipsize=$(gzip -c "$1" | wc -c)
	local ratio=$(echo "$gzipsize * 100 / $origsize" | bc -l)
	printf "orig: %d bytes\n" "$origsize"
	printf "gzip: %d bytes (%2.2f%%)\n" "$gzipsize" "$ratio"
}
