#!/bin/sh
#
# Usage: tre
# Description: `tre` is a shorthand for `tree` with hidden files and color enabled,
# ignoring the `.git` directory, listing directories first. The output gets piped
# into `less` with options to preserve color and line numbers, unless the output is
# small enough for one screen.
#
# credit: https://github.com/mathiasbynens/dotfiles/blob/main/.functions

tre() {
	tree -aC -I '.git|node_modules' --dirsfirst "$@" | less -FRNX
}
