#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

install_scripts="**/install.sh"
regex_scripts_to_run_first="(homebrew|zsh)\/install.sh"

# Run homebrew and zsh first
for script in $install_scripts
	do
		if [[ $script =~ $regex_scripts_to_run_first ]]
			then
				sh -c "${script}"
		fi
done

# Then everything else
for script in $install_scripts
	do
		if ! [[ $script =~ $regex_scripts_to_run_first ]]
			then
				sh -c "${script}"
		fi
done
