#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Run homebrew first
homebrew/install.sh

# Then everything else
for script in **/install.sh
	do
		if ! [[ $script == homebrew* ]]
			then
				sh -c "${script}"
		fi
done
